# Generated by Django 4.0.5 on 2022-06-09 22:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_autor_estado_categoria_estado_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Contenido'),
        ),
    ]
