# Generated by Django 4.0.5 on 2022-06-09 22:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=' ', verbose_name='Contenido'),
        ),
    ]
