# Generated by Django 4.0.5 on 2022-06-12 00:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_post_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='post',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Cuerpo'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default='', max_length=110, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(max_length=1100, upload_to=''),
        ),
    ]
