# Generated by Django 4.0.5 on 2022-06-12 00:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_remove_post_contenido_remove_post_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=110, verbose_name='Subtítulo'),
        ),
    ]
